[package]
name = "bills"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
clap_lex = "0.7.4"
rgb = "0.8.50"
term_size = "0.3.2"
textplots = "0.8.7"
toml = "0.8.20"
